version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      runtime:
        patterns: ["next", "react", "react-dom", "zod"]
      testing-and-tooling:
        dependency-type: development
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
